title: Guimarães, Rodolfo Labiapari Mansur
exclude:
- README.md
- LICENSE.md
- changelog.md
theme: minima

authors:
  rlmg:
    name: Rodolfo Labiapari Mansur Guimarães
    display_name: rodolfo_lab
    email: rodolfolabiapari@gmail.com
