title: Rodolfo Labiapari Mansur Guimarães 🎈
theme: minima

author:
  name: Rodolfo Labiapari Mansur Guimarães, MSc
  display_name: rodolfo_lab
  email: rodolfolabiapari@gmail.com
  pgpsite: https://keys.openpgp.org/search?q=E240754FEDFB405556D82A173A0990FAE12D319E
  pgp: E240754FEDFB405556D82A173A0990FAE12D319E
  bitcoin: 3QMWVgnDu6pwZuVrvmpQw6arQqVKi2sxcJ

# The `>` after `description:` means to ignore line-breaks until next key.
# If you want to omit the line-break after the end of text, use `>-` instead.
description: >
  Always, always in construction.

# Build settings

# If you clone the Minima repo and build locally, use this setting.
theme: minima

# As of November 2023, GitHub Pages still uses Minima 2.5.1 (https://pages.github.com/versions/). 
# If you want to use the latest Minima version on GitHub Pages, use the following setting and 
# add a line comment on "theme: minima" above.
#remote_theme: jekyll/minima

plugins:
  - jekyll-seo-tag

# Theme-specific settings

# If you want to link only specific pages in your header, use this and add the path to the pages
# in order as they should show up.
header_pages:
  - about.md

# Set to `true` to show excerpts on the homepage.
#show_excerpts: false

# Minima specific settings, which are only available from Minima 3.0 onward.
minima:
  # Minima skin selection.
  # Available skins are:
  # classic	           Default, light color scheme.
  # dark	             Dark variant of the classic skin.
  # auto	             Adaptive skin based on the default classic and dark skins.
  # solarized-light	   Light variant of solarized color scheme.
  # solarized-dark	   Dark variant of solarized color scheme.
  # solarized	         Adaptive skin for solarized color scheme skins.
  skin: classic
  
  # Minima date format.
  # The default value is "%b %d, %Y" (e.g. Nov 14, 2023) 
  # Refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this.
  date_format: "%d %b %Y"

  # Generate social links in footer.
  social_links:
    - { platform: facebook,       user_url: "https://www.facebook.com/rodolfolabiapari" }
    - { platform: github,         user_url: "https://github.com/rodolfolabiapari" }
    - { platform: google_scholar, user_url: "https://scholar.google.com/citations?user=wB6tRu0AAAAJ" }
    - { platform: instagram,      user_url: "https://www.instagram.com/rodolfo_lab/" }
    - { platform: linkedin,       user_url: "https://linkedin.com/in/rodolfolabiapari" }
    - { platform: twitter,        user_url: "https://twitter.com/rodolfo_lab" }
    - { platform: youtube,        user_url: "https://www.youtube.com/@rodolfo_lab" }
